version: "3.7"

services:
  biweb:
    image: biweb
    build:
      context: ./bi-web
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    container_name: biweb
    depends_on:
      - biwaf
      - biapi
    ports:
      - 8082:8080
    networks:
      upstream:
      backend:
  biapi:
    container_name: biapi
    image: biapi
    build:
      context: ./bi-api
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - bidb
      - brapi-server
    environment:
      - API_INTERNAL_PORT=${API_INTERNAL_PORT:-8081}
      - DB_SERVER=${DB_SERVER:-dbserver:5432}
      - DB_NAME=${DB_NAME:-bidb}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - JWT_DOMAIN=${JWT_DOMAIN:-localhost}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - GITHUB_ACTOR=${GITHUB_ACTOR}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BRAPI_CORE_URL=${BRAPI_CORE_URL}
      - BRAPI_PHENO_URL=${BRAPI_PHENO_URL}
      - BRAPI_GENO_URL=${BRAPI_GENO_URL}
      - BRAPI_REFERENCE_SOURCE=${BRAPI_REFERENCE_SOURCE}
      - WEB_BASE_URL=${WEB_BASE_URL}
    ports:
      - 8081:8081
    networks:
      backend:
      protected:
  brapi-server:
    image: breedinginsight/brapi-java-server
    container_name: brapi-server
    depends_on:
      - bidb
    environment:
      - BRAPI_DB_SERVER=${BRAPI_DB_SERVER}
      - BRAPI_DB=${BRAPI_DB}
      - BRAPI_DB_USER=${BRAPI_DB_USER}
      - BRAPI_DB_PASSWORD=${BRAPI_DB_PASSWORD}
    ports:
      - ${BRAPI_SERVER_PORT}:8080
    volumes:
      - ./bi-api/src/main/resources/brapi/properties/application.properties:/home/brapi/properties/application.properties
      - ./bi-api/src/main/resources/brapi/sql/:/home/brapi/sql/
    networks:
      protected:
        aliases:
          - brapiserver
      backend:
        aliases:
          - brapiserver
  bidb: 
    image: postgres:11.4
    environment:
      POSTGRES_DB: 'bidb'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: bidb
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: biapi_data
        target: /var/lib/postgresql/data
    networks:
      protected:
        aliases:
          - dbserver  
  biwaf:
    image: franbuehler/modsecurity-crs-rp
    container_name: waf
    environment:
      - PORT=8001
      - BACKEND=http://biweb:8080
      - PARANOIA=1
      - ANOMALYIN=5
      - ANOMALYOUT=4
    ports:
      - 80:8001
    networks:
      frontend:
      upstream:

networks:
  frontend:
  upstream:
  backend:
  protected:

volumes:
  biapi_data:
    name: biapi_data