version: "3.7"

services:
  gigwa:
    depends_on:
      - mongo
    image: breedinginsight/gigwa:2.5.2-snapshot
    container_name: gigwa
    ports:
      - "5080:8080"
    restart: always
    environment:
      MONGO_IP: gigwa_db
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${GIGWA_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${GIGWA_MONGO_PASSWORD}
      HOST_LOCALE: "${LANG}"
    networks:
      backend:
    volumes:
      - type: volume
        source: gigwa_data
        target: /usr/local/tomcat/config
  mongo:
    image: mongo:4.2.21
    container_name: gigwa_db
    restart: always
    command: --profile 0 --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zstd --directoryperdb --quiet
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GIGWA_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${GIGWA_MONGO_PASSWORD}
    volumes:
      - type: volume
        source: gigwa_mongo_data
        target: /data/db
    networks:
      backend:

volumes:
  gigwa_data:
    name: gigwa_data
  gigwa_mongo_data:
    name: gigwa_mongo_data
