version: "3.7"

services:
  gigwa:
    image: breedinginsight/gigwa:rc
  biweb:
    image: breedinginsight/biweb:rc
  biapi:
    image: breedinginsight/biapi:rc
  brapi-server:
    image: breedinginsight/brapi-java-server:rc
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - ${MAILHOG_WEB_PORT:-8025}:8025
      - ${MAILHOG_PORT:-1025}:1025
    networks:
      backend: