version: "3.7"

services:
  biweb:
    image: breedinginsight/biweb:develop
    build:
      context: ./bi-web
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: ./bi-web/src
        target: /home/host/biweb/src/
      - type: bind
        source: ./bi-web/task
        target: /home/host/biweb/task/
      - type: bind
        source: ./bi-web/tests
        target: /home/host/biweb/tests/
      - type: bind
        source: ./bi-web/public
        target: /home/host/biweb/public/
  biapi:
    image: breedinginsight/biapi:develop
    build:
      context: ./bi-api
      dockerfile: ./Dockerfile-dev
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    ports:
      - 8090:8081
    volumes:
      - type: bind
        source: ./bi-api/
        target: /biapi/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
    environment:
      - GITHUB_ACTOR=${GITHUB_ACTOR}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
  brapi-server:
    volumes:
      - ./bi-api/src/main/resources/brapi/properties/application.properties:/home/brapi/properties/application.properties
      - ./bi-api/src/main/resources/brapi/sql/:/home/brapi/sql/
    ports:
      - ${BRAPI_SERVER_PORT}:8080    
  mailhog:
    ports:
      - 1025:1025
  bidb:
    ports:
      - 5432:5432
  # biwaf:
  #   ports:
  #     - 8089:8001


