version: "3.7"

services:
  redis:
    image: redis:7.2.0
    container_name: ${REDIS_CONTAINER_NAME:-redis}
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: always
    networks:
      backend:
