version: "3.7"

services:
  biweb:
    image: biweb
    build:
      context: ./bi-web
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    container_name: biweb
    depends_on:
      - biwaf
      - biapi-dev
    volumes:
      - type: bind
        source: ./bi-web/src
        target: /home/host/biweb/src/
      - type: bind
        source: ./bi-web/task
        target: /home/host/biweb/task/
      - type: bind
        source: ./bi-web/tests
        target: /home/host/biweb/tests/
      - type: bind
        source: ./bi-web/public
        target: /home/host/biweb/public/
    ports:
      - 8082:8080
    networks:
      upstream:
      backend:
  biapi-dev:
    container_name: biapi
    image: biapi
    build:
      context: ./bi-api
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - bidb
      - brapi-server
    volumes:
      - type: bind
        source: ./bi-api/
        target: /biapi/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
      - type: bind
        source: ../.m2
        # target: /home/host/.m2
        target: /root/.m2
    environment:
      - API_INTERNAL_PORT=8081
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - JWT_DOMAIN=localhost
      - DB_SERVER=dbserver:5432
      - DB_NAME=bidb
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_DOMAIN=${JWT_DOMAIN:-localhost}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - GITHUB_ACTOR=${GITHUB_ACTOR}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BRAPI_CORE_URL=${BRAPI_CORE_URL}
      - BRAPI_PHENO_URL=${BRAPI_PHENO_URL}
      - BRAPI_GENO_URL=${BRAPI_GENO_URL}
      - BRAPI_REFERENCE_SOURCE=${BRAPI_REFERENCE_SOURCE}
    ports:
      - 8081:8081
    networks:
      backend:
      protected:
  brapi-server:
    image: breedinginsight/brapi-java-server
    container_name: brapi-server
    depends_on:
      - bidb
    environment:
      - BRAPI_DB_SERVER=${BRAPI_DB_SERVER}
      - BRAPI_DB=${BRAPI_DB}
      - BRAPI_DB_USER=${BRAPI_DB_USER}
      - BRAPI_DB_PASSWORD=${BRAPI_DB_PASSWORD}
    ports:
      - ${BRAPI_SERVER_PORT}:8080
    volumes:
      - ./bi-api/src/main/resources/brapi/properties/application.properties:/home/brapi/properties/application.properties
      - ./bi-api/src/main/resources/brapi/sql/:/home/brapi/sql/
    networks:
      protected:
        aliases:
          - brapiserver
      backend:
        aliases:
          - brapiserver
  bidb: 
    image: postgis/postgis:12-3.0
    environment:
      - POSTGRES_DB=bidb
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: bidb
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: biapi_data
        target: /var/lib/postgresql/data
    networks:
      protected:
        aliases:
          - dbserver  
  biwaf:
    image: franbuehler/modsecurity-crs-rp
    container_name: waf
    environment:
      - PORT=8001
      - BACKEND=http://biweb:8080
      - PARANOIA=1
      - ANOMALYIN=5
      - ANOMALYOUT=4
    ports:
      - 8080:8001
    networks:
      frontend:
      upstream:

networks:
  frontend:
  upstream:
  backend:
  protected:

volumes:
  biapi_data:
    name: biapi_data