version: "3.7"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"
    networks:
      backend:
        aliases:
          - localstack
    environment:
      - HOSTNAME_EXTERNAL=localstack
