version: "3.7"

services:
  biweb:
    image: biweb
    build:
      context: ./bi-web
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    container_name: biweb
    depends_on:
      - biapi
    networks:
      upstream:
  biapi:
    container_name: biapi
    image: biapi
    build:
      context: ./bi-api
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - bidb
      - brapi-server
    environment:
      - API_INTERNAL_PORT=${API_INTERNAL_PORT:-8081}
      - DB_SERVER=${DB_SERVER:-dbserver:5432}
      - DB_NAME=${DB_NAME:-bidb}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - JWT_DOMAIN=${JWT_DOMAIN:-localhost}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - GITHUB_ACTOR=${GITHUB_ACTOR}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BRAPI_CORE_URL=${BRAPI_CORE_URL}
      - BRAPI_PHENO_URL=${BRAPI_PHENO_URL}
      - BRAPI_GENO_URL=${BRAPI_GENO_URL}
      - BRAPI_REFERENCE_SOURCE=${BRAPI_REFERENCE_SOURCE}
      - WEB_BASE_URL=${WEB_BASE_URL}
      - EMAIL_RELAY_HOST=${EMAIL_RELAY_HOST}
      - EMAIL_RELAY_PORT=${EMAIL_RELAY_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
    networks:
      backend:
      protected:
  brapi-server:
    image: breedinginsight/brapi-java-server
    container_name: brapi-server
    depends_on:
      - bidb
    environment:
      - BRAPI_DB_SERVER=${BRAPI_DB_SERVER}
      - BRAPI_DB=${BRAPI_DB}
      - BRAPI_DB_USER=${BRAPI_DB_USER}
      - BRAPI_DB_PASSWORD=${BRAPI_DB_PASSWORD}
    volumes:
      - ./bi-api/src/main/resources/brapi/properties/application.properties:/home/brapi/properties/application.properties
      - ./bi-api/src/main/resources/brapi/sql/:/home/brapi/sql/
    networks:
      backend:
        aliases:
          - brapiserver
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - 8025:8025
    networks:
      backend:
  bidb: 
    image: postgres:11.4
    environment:
      POSTGRES_DB: 'bidb'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: bidb
    volumes:
      - type: volume
        source: biapi_data
        target: /var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - dbserver  
  # biwaf:
  #   image: franbuehler/modsecurity-crs-rp
  #   container_name: waf
  #   environment:
  #     - PORT=8001
  #     - BACKEND=http://biapi:8081
  #     - PARANOIA=1
  #     - ANOMALYIN=5
  #     - ANOMALYOUT=4
  #   networks:
  #     protected:
  #       aliases:
  #         - waf
  #     upstream:
  #       aliases:
  #         - waf
  biproxy:
    container_name: biproxy    
    image: biproxy
    build:
      dockerfile: biproxy.docker
      context: ./proxy
      args:
        - REGISTERED_DOMAIN=${REGISTERED_DOMAIN:-localhost}
        - WAF_IP=biapi:8081
        - WEB_IP=biweb:8080
    depends_on:
      - biapi
      - biweb
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: tls_certs
        target: /etc/letsencrypt
      - type: volume
        source: proxy_config
        target: /etc/nginx/conf.d
    networks:
      upstream:
      protected:
      
networks:
  upstream:
  backend:
  protected:

volumes:
  proxy_config:
    name: proxy_config
  tls_certs:
    name: tls_certs
  biapi_data:
    name: biapi_data
