version: "3.7"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    networks:
      backend:
        aliases:
          - localstack
    environment:
      - LOCALSTACK_HOST=localstack
