version: "3.7"

services:
  biweb:
    image: breedinginsight/biweb:ci
    build:
      context: ./bi-web
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    ports:
      - ${WEB_EXTERNAL_PORT:-8083}:8080
  biapi:
    depends_on:
      - redis
      - gigwa
    image: breedinginsight/biapi:ci
    build:
      context: ./bi-api
      dockerfile: ./Dockerfile-dev
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    ports:
      - ${API_EXTERNAL_PORT:-8090}:8081
    environment:
      - GITHUB_ACTOR=${GITHUB_ACTOR}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT:-30s}
      - REDIS_SSL=${REDIS_SSL:-false}
      - GIGWA_HOST=${GIGWA_HOST:-http://gigwa:8080}
  brapi-server:
    image: breedinginsight/brapi-java-server:develop
    ports:
      - ${BRAPI_SERVER_PORT:-8080}:8080
  bidb:
    ports:
      - ${DB_PORT:-5432}:5432


