version: "3.7"

services:
  biweb:
    image: breedinginsight/biweb:develop
  biapi:
    image: breedinginsight/biapi:develop
    depends_on:
      - bidb
      - brapi-server
      - redis
      - gigwa
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT:-30s}
      - REDIS_SSL=${REDIS_SSL:-false}
      - GIGWA_HOST=${GIGWA_HOST:-http://gigwa:8080}
  bidb:
    ports:
      - ${DB_PORT:-5432}:5432
