version: "3.7"

services:
  gigwa:
    image: breedinginsight/gigwa:develop
  biweb:
    image: breedinginsight/biweb:develop
  biapi:
    image: breedinginsight/biapi:develop
    depends_on:
      - bidb
      - brapi-server
      - redis
      - gigwa
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT:-30s}
      - REDIS_SSL=${REDIS_SSL:-false}
      - GIGWA_HOST=${GIGWA_HOST:-http://gigwa:8080}
  brapi-server:
    image: breedinginsight/brapi-java-server:develop
  bidb:
    ports:
      - ${DB_PORT:-5432}:5432
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - ${MAILHOG_WEB_PORT:-8025}:8025
      - ${MAILHOG_PORT:-1025}:1025
    networks:
      backend:
